spring:
  datasource: 
    username: hospital
    password: hospital
    url: jdbc:mysql://localhost:3306/hospital
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  
  sql:
    init:
      mode: never 